apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: smart-city
type: Opaque
stringData:
  # PostgreSQL
  postgres-user: smart_city
  postgres-password: smartcity123
  postgres-db: smart_city_db
  
  # MongoDB
  mongo-root-user: admin
  mongo-root-password: smartcity123
  mongo-db: smart_city
  
  # Redis (pas de mot de passe par d√©faut)
  redis-password: ""
