apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: infinity
    isDefault: false
    jsonData:
      oauthPassThru: true
      timeoutInSeconds: 60
      allowedHosts:
        - "http://api:8000"
        - "http://smart-city-api:8000"
        - "http://localhost:8000"
        - "http://127.0.0.1:8000"
      global_queries:
        - name: "API Base URL"
          id: "api_base"
          query: "http://api:8000"
    secureJsonData: {}
    editable: true
