apiVersion: 1

datasources:
  - name: Infinity-API
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: infinity-api
    isDefault: false
    jsonData:
      oauthPassThru: false
      timeoutInSeconds: 60
      # Configuration des hôtes autorisés
      allowedHosts:
        - "http://api:8000"
        - "http://smart-city-api:8000"
        - "http://localhost:8000"
        - "http://127.0.0.1:8000"
        - "http://host.docker.internal:8000"
      # Headers par défaut
      httpHeaderName1: "Content-Type"
      httpHeaderValue1: "application/json"
      # Configuration de base
      global_queries:
        - name: "Smart City API Base"
          id: "smart_city_api"
          query: "http://api:8000/api/v1"
      # Options supplémentaires
      proxy_url: ""
      is_default: false
      with_credentials: false
      tls_skip_verify: true
    secureJsonData: {}
    editable: true
